version: '3'

services:
  hypothesis_sqlalchemy-pypy:
    build:
      context: .
      args:
        - IMAGE_NAME=${PYPY_IMAGE_NAME}
        - IMAGE_VERSION=${PYPY_IMAGE_VERSION}
    image: lycantropos/hypothesis_sqlalchemy-pypy:1.1.0-alpha
    volumes:
      - ./hypothesis_sqlalchemy:/opt/hypothesis_sqlalchemy/hypothesis_sqlalchemy
      - ./pytest.ini:/opt/hypothesis_sqlalchemy/pytest.ini
      - ./README.md:/opt/hypothesis_sqlalchemy/README.md
      - ./requirements-tests.txt:/opt/hypothesis_sqlalchemy/requirements-tests.txt
      - ./requirements.txt:/opt/hypothesis_sqlalchemy/requirements.txt
      - ./setup.py:/opt/hypothesis_sqlalchemy/setup.py
      - ./tests:/opt/hypothesis_sqlalchemy/tests
    entrypoint: pytest
